/**
 * One-shot script. Llegeix el PDF de Reus Refugi (que té widgets AcroForm) i
 * extreu les coordenades de cada widget per pintar-les hardcoded al codi.
 *
 * El motiu: el PDF oficial buit del Ministeri (inclusion.gob.es) NO té camps
 * AcroForm — és un PDF estàtic generat des de Word. Per fer-lo servir com a
 * template open-source net (sense rastres de Reus Refugi) usem aquest PDF
 * oficial + pintem tot a coordenades absolutes.
 *
 * Run:  npx tsx scripts/extract-anexo2-coords.ts
 */

import { readFile } from "node:fs/promises";
import {
  PDFDocument,
  PDFName,
  PDFArray,
  PDFDict,
  PDFRef,
  PDFNumber,
  PDFString,
  PDFHexString,
} from "pdf-lib";

interface Widget {
  pageIndex: number;
  name: string;
  type: "Tx" | "Btn" | "Sig" | "?";
  rect: { x: number; y: number; w: number; h: number };
}

async function main() {
  const bytes = await readFile("/tmp/A2_original_backup.pdf");
  const pdfDoc = await PDFDocument.load(bytes);
  const widgets: Widget[] = [];

  const pages = pdfDoc.getPages();
  for (let i = 0; i < pages.length; i++) {
    const annots = pages[i].node.lookup(PDFName.of("Annots"));
    if (!(annots instanceof PDFArray)) continue;
    for (let k = 0; k < annots.size(); k++) {
      const item = annots.get(k);
      const dict = item instanceof PDFRef ? pdfDoc.context.lookup(item) : item;
      if (!(dict instanceof PDFDict)) continue;
      const subtype = dict.lookup(PDFName.of("Subtype"));
      if (!(subtype instanceof PDFName) || subtype.asString() !== "/Widget") continue;

      const t = dict.lookup(PDFName.of("T"));
      const name =
        t instanceof PDFString ? t.decodeText()
        : t instanceof PDFHexString ? t.decodeText()
        : "";
      if (!name) continue;

      const rectArr = dict.lookup(PDFName.of("Rect"));
      if (!(rectArr instanceof PDFArray) || rectArr.size() < 4) continue;
      const r = [0, 1, 2, 3].map((j) => {
        const v = rectArr.get(j);
        return v instanceof PDFNumber ? v.asNumber() : NaN;
      });
      if (r.some(Number.isNaN)) continue;

      const ft = dict.lookup(PDFName.of("FT"));
      const ftStr = ft instanceof PDFName ? ft.asString() : "";
      const type: Widget["type"] =
        ftStr === "/Tx" ? "Tx"
        : ftStr === "/Btn" ? "Btn"
        : ftStr === "/Sig" ? "Sig"
        : "?";

      widgets.push({
        pageIndex: i,
        name,
        type,
        rect: {
          x: Math.min(r[0], r[2]),
          y: Math.min(r[1], r[3]),
          w: Math.abs(r[2] - r[0]),
          h: Math.abs(r[3] - r[1]),
        },
      });
    }
  }

  // Sort by page then name (numeric where possible)
  widgets.sort((a, b) => {
    if (a.pageIndex !== b.pageIndex) return a.pageIndex - b.pageIndex;
    const na = parseInt(a.name.match(/\d+/)?.[0] ?? "0", 10);
    const nb = parseInt(b.name.match(/\d+/)?.[0] ?? "0", 10);
    return na - nb;
  });

  console.log("// Auto-generated by scripts/extract-anexo2-coords.ts");
  console.log("// Coordinates of every form widget in the original Reus Refugi-");
  console.log("// authored A2 PDF. We hardcode these so the runtime can paint");
  console.log("// onto the official ministry-issued blank PDF (which has no");
  console.log("// AcroForm of its own).");
  console.log("export interface AnexoIIWidgetCoord {");
  console.log("  page: 0 | 1;");
  console.log("  type: \"text\" | \"check\" | \"signature\";");
  console.log("  x: number; y: number; w: number; h: number;");
  console.log("}");
  console.log("export const ANEXO2_COORDS: Record<string, AnexoIIWidgetCoord> = {");
  for (const w of widgets) {
    const t =
      w.type === "Tx" ? "text"
      : w.type === "Btn" ? "check"
      : w.type === "Sig" ? "signature"
      : "text";
    console.log(
      `  ${JSON.stringify(w.name)}: { page: ${w.pageIndex}, type: ${JSON.stringify(t)}, x: ${w.rect.x.toFixed(2)}, y: ${w.rect.y.toFixed(2)}, w: ${w.rect.w.toFixed(2)}, h: ${w.rect.h.toFixed(2)} },`,
    );
  }
  console.log("};");
}

main().catch((e) => { console.error(e); process.exit(1); });
