// Auto-generated by scripts/extract-anexo2-coords.ts
// Coordinates of every form widget in the original Reus Refugi-
// authored A2 PDF. We hardcode these so the runtime can paint
// onto the official ministry-issued blank PDF (which has no
// AcroForm of its own).
export interface AnexoIIWidgetCoord {
  page: 0 | 1;
  type: "text" | "check" | "signature";
  x: number; y: number; w: number; h: number;
}
export const ANEXO2_COORDS: Record<string, AnexoIIWidgetCoord> = {
  "Casilla de verificación52": { page: 0, type: "check", x: 71.15, y: 585.88, w: 6.33, h: 7.67 },
  "Casilla de verificación53": { page: 0, type: "check", x: 70.82, y: 567.72, w: 6.33, h: 7.67 },
  "Casilla de verificación54": { page: 0, type: "check", x: 34.83, y: 288.77, w: 6.33, h: 7.67 },
  "Casilla de verificación55": { page: 0, type: "check", x: 34.83, y: 263.77, w: 6.33, h: 7.67 },
  "Casilla de verificación56": { page: 0, type: "check", x: 34.83, y: 238.44, w: 6.33, h: 7.67 },
  "Casilla de verificación57": { page: 0, type: "check", x: 34.83, y: 212.78, w: 6.33, h: 7.67 },
  "Casilla de verificación58": { page: 0, type: "check", x: 35.17, y: 187.45, w: 6.33, h: 7.67 },
  "Casilla de verificación59": { page: 0, type: "check", x: 35.17, y: 162.12, w: 6.33, h: 7.67 },
  "Casilla de verificación60": { page: 0, type: "check", x: 35.17, y: 136.79, w: 6.33, h: 7.67 },
  "Casilla de verificación61": { page: 0, type: "check", x: 35.18, y: 111.12, w: 6.33, h: 7.67 },
  "Casilla de verificación62": { page: 0, type: "check", x: 34.84, y: 86.46, w: 6.33, h: 7.67 },
  "Casilla de verificación63": { page: 0, type: "check", x: 35.51, y: 60.46, w: 6.33, h: 7.67 },
  "Casilla de verificación64": { page: 0, type: "check", x: 34.83, y: 35.15, w: 6.33, h: 7.67 },
  "Texto145": { page: 0, type: "text", x: 116.48, y: 663.87, w: 456.91, h: 11.33 },
  "Texto146": { page: 0, type: "text", x: 76.49, y: 626.54, w: 494.57, h: 11.33 },
  "Texto147": { page: 0, type: "text", x: 190.13, y: 537.22, w: 305.61, h: 11.33 },
  "Texto148": { page: 0, type: "text", x: 73.29, y: 514.56, w: 478.58, h: 11.33 },
  "Texto149": { page: 0, type: "text", x: 97.15, y: 491.57, w: 444.25, h: 11.33 },
  "Texto150": { page: 0, type: "text", x: 109.15, y: 450.24, w: 428.59, h: 11.33 },
  "Texto151": { page: 0, type: "text", x: 136.21, y: 427.31, w: 389.26, h: 11.33 },
  "Texto152": { page: 0, type: "text", x: 114.81, y: 404.25, w: 424.25, h: 11.33 },
  "Texto153": { page: 0, type: "text", x: 86.22, y: 380.52, w: 460.58, h: 11.33 },
  "Texto154": { page: 0, type: "text", x: 71.82, y: 357.59, w: 264.95, h: 11.33 },
  "Texto155": { page: 0, type: "text", x: 397.09, y: 357.93, w: 127.98, h: 11.33 },
  "Texto156": { page: 0, type: "text", x: 73.49, y: 331.93, w: 142.31, h: 11.33 },
  "Texto157": { page: 0, type: "text", x: 237.79, y: 332.93, w: 78.99, h: 11.33 },
  "Texto158": { page: 0, type: "text", x: 354.77, y: 332.60, w: 173.63, h: 11.33 },
  "Signature": { page: 1, type: "signature", x: 398.75, y: 586.45, w: 89.56, h: 43.90 },
  "Casilla de verificación65": { page: 1, type: "check", x: 34.50, y: 786.42, w: 6.33, h: 7.67 },
  "Texto159": { page: 1, type: "text", x: 116.81, y: 785.18, w: 419.59, h: 11.33 },
  "Texto160": { page: 1, type: "text", x: 211.46, y: 610.54, w: 207.63, h: 11.33 },
  "Texto161": { page: 1, type: "text", x: 61.16, y: 563.82, w: 196.63, h: 11.33 },
  "Texto162": { page: 1, type: "text", x: 250.12, y: 520.23, w: 44.99, h: 11.33 },
  "Texto163": { page: 1, type: "text", x: 343.77, y: 519.23, w: 17.66, h: 11.33 },
  "Texto164": { page: 1, type: "text", x: 400.76, y: 519.56, w: 57.99, h: 11.33 },
};
